# -*- coding: utf-8 -*-
"""Copy of Eddie's Final Project Data Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qIrgu266V3cxu2w69M6j0Bc9XBZuCeJs

Exploratory Data Inverstigation
"""

import kagglehub
path = kagglehub.dataset_download("alexteboul/diabetes-health-indicators-dataset")

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import (
    classification_report, roc_auc_score,
    confusion_matrix, RocCurveDisplay
)

files = os.listdir(path)
print(files)

file = os.path.join(path, files[0])
df = pd.read_csv(file)

# Split dataset into x (observations) and y (diabetes) and a list of the all the feature

x = df.drop(columns=['Diabetes_binary'])
y = df['Diabetes_binary'].astype(int)
feature_names = x.columns.tolist()

print(feature_names)

# split the dataset by 5 fold for cross validation
# stratified y to make sure there is an equal 50/50 for both the training set and testing set
# set a random seed to make sure we get consistent data for easy debugging

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=67, stratify=y)

# normalize data so that binary and continuous data have equal weight in our model
# normalize training and testing data separately to prevent data leakage
# because testing data should not affect our model

scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled  = scaler.transform(x_test)

# Performed LASSO regularization with our selected C value such
# that we reduce as many variables as possible without sacrificing accuracy

best_C_auc = 0.0022

print(f"LASSO regularized logistic regression with C={best_C_auc} based on AUC\n")

final_auc_model = LogisticRegression(
    penalty='l1',
    solver='liblinear',
    C=best_C_auc,
    max_iter=1000,
    random_state=67
)
final_auc_model.fit(x_train_scaled, y_train)

coef = pd.Series(final_auc_model.coef_[0], index=feature_names)
selected = coef[coef != 0].sort_values(ascending=False)
unselected = coef[coef == 0]

print(f"\n  Lasso selected {len(selected)} out of {len(feature_names)} features.")
print(f"\n  Unselected features were\n{unselected}\n")
print(f"  {'Feature':<25}  {'Coefficient':>12}  {'Effect on Diabetes Risk'}")
print("  " + "-" * 65)
for feat, val in selected.items():
    direction = "↑ INCREASES risk" if val > 0 else "↓ decreases risk"
    print(f"  {feat:<25}  {val:>12.4f}  {direction}")

# Plot the coefficients of each feature in the LASSO regularized logistic model

coef_all = pd.Series(final_auc_model.coef_[0], index=feature_names).sort_values(ascending=True)

# 2. Define colors: Red for increasing risk (>0), Blue for decreasing risk (<0)
colors = ['#e74c3c' if val > 0 else '#3498db' for val in coef_all.values]

# 3. Create the horizontal bar plot
plt.figure(figsize=(12, 8))
bars = plt.barh(coef_all.index, coef_all.values, color=colors, edgecolor='none')

# 4. Add a vertical line at 0 for reference
plt.axvline(x=0, color='black', linestyle='-', linewidth=0.8, alpha=0.7)

# 5. Styling and labels
plt.title('Impact of Features on Diabetes Risk (Logistic Regression Coefficients measured with AUC)', fontsize=14, fontweight='bold', pad=15)
plt.xlabel('Coefficient Value (Log-Odds Scale)', fontsize=12)
plt.ylabel('Features', fontsize=12)
plt.grid(axis='x', linestyle='--', alpha=0.5)

# 6. Optional: Add value labels next to the bars for exact precision
for bar in bars:
    width = bar.get_width()
    # Position text based on whether it's positive or negative
    if width >= 0:
        plt.text(width + 0.01, bar.get_y() + bar.get_height()/2, f'{width:.4f}',
                 va='center', ha='left', fontsize=10, color='black')
    else:
        plt.text(width - 0.01, bar.get_y() + bar.get_height()/2, f'{width:.4f}',
                 va='center', ha='right', fontsize=10, color='black')

# 7. Prevent label truncation and display
plt.tight_layout()
plt.show()